from abc import ABC, abstractmethod
from PIL import Image

class BaseValidator(ABC):
    def __init__(self,base_model):
        """
        Base class for image validators.
        Subclasses should implement the validate method.
        """
        self.base_model = base_model
    
    @abstractmethod
    def validate(self, image: Image.Image, class_name: str) -> dict:
        """
        Validate the given cropped image for the predicted class.
        Returns a dict: { 'label': str, 'confidence': float }
        Confidence should be between 0.0 and 1.0.
        """
        pass
    
    def inference(image, prompt, temp=0.5):
    """
    Performs inference using Google Gemini 2.5 Pro Experimental model.

    Args:
        image (str or genai.types.Blob): The image input, either as a base64-encoded string or Blob object.
        prompt (str): A text prompt to guide the model's response.
        temp (float, optional): Sampling temperature for response randomness. Default is 0.5.

    Returns:
        str: The text response generated by the Gemini model based on the prompt and image.
    """
    response = client.models.generate_content(
        model="gemini-2.5-flash-preview-05-20",  # or "gemini-2.5-pro-exp-03-25"
        contents=[prompt, image],  # Provide both the text prompt and image as input
        config=types.GenerateContentConfig(
            temperature=temp,  # Controls creativity vs. determinism in output
        ),
    )

    return response.text  # Return the generated textual response 