
import json

import cv2
import ultralytics
from google import genai
from google.genai import types
from PIL import Image
from ultralytics.utils.downloads import safe_download
from ultralytics.utils.plotting import Annotator, colors
import matplotlib.pyplot as plt
import numpy as np
# ultralytics.checks()


# Initialize the Gemini client with your API key
client = genai.Client(api_key="AIzaSyAB8IE5VyPgfpIUr-7xMDoiW9SVYkb7tF0")


def inference(image, prompt, temp=0.5):
    """
    Performs inference using Google Gemini 2.5 Pro Experimental model.

    Args:
        image (str or genai.types.Blob): The image input, either as a base64-encoded string or Blob object.
        prompt (str): A text prompt to guide the model's response.
        temp (float, optional): Sampling temperature for response randomness. Default is 0.5.

    Returns:
        str: The text response generated by the Gemini model based on the prompt and image.
    """
    response = client.models.generate_content(
        # model="gemini-2.5-flash-preview-05-20",  # or "gemini-2.5-pro-exp-03-25"
        model="gemini-2.5-pro",
        contents=[prompt, image],  # Provide both the text prompt and image as input
        config=types.GenerateContentConfig(
            temperature=temp,  # Controls creativity vs. determinism in output
        ),
    )

    return response.text  # Return the generated textual response


def read_image(filename=None):
    if filename is not None:
        image_name = filename
    else:
        image_name = "bus.jpg"  # or "zidane.jpg"

    # Download the image
    # safe_download(f"https://github.com/ultralytics/notebooks/releases/download/v0.0.0/{image_name}")

    # Read image with opencv
    image = cv2.cvtColor(cv2.imread(f"{image_name}"), cv2.COLOR_BGR2RGB)

    # Extract width and height
    h, w = image.shape[:2]

    # # Read the image using OpenCV and convert it into the PIL format
    return Image.fromarray(image), w, h


def clean_results(results):
    """Clean the results for visualization."""
    return results.strip().removeprefix("```json").removesuffix("```").strip()


# Define the text prompt
# prompt = """
# Detect the 2d bounding boxes of objects in image.
# """

# prompt = """
# Detect the 2d bounding boxes of objects in image.
# """

# # Fixed, plotting function depends on this.
# output_prompt = "Return just box_2d and labels, no additional text."


# Define the text prompt
prompt = """
Detect the 2d bounding box around:
highlight the area off all visible license plates in each car.
"""

# Fixed, plotting function depends on this.
output_prompt = """
Return just box_2d which will be location of detected text areas + label, the label will be license plate number , 
use OCR to extract the the plate number, if license plate is not clear ignore it , no additional text.
"""

image, w, h = read_image("./trafic5.jpg")  # Read img, extract width, height


print("Starting inference...")
results = inference(image, prompt + output_prompt)  # Perform inference
print(results)
cln_results = json.loads(clean_results(results))  # Clean results, list convert

annotator = Annotator(image)  # initialize Ultralytics annotator

for idx, item in enumerate(cln_results):
    # By default, gemini model return output with y coordinates first.
    # Scale normalized box coordinates (0–1000) to image dimensions
    y1, x1, y2, x2 = item["box_2d"]  # bbox post processing,
    y1 = y1 / 1000 * h
    x1 = x1 / 1000 * w
    y2 = y2 / 1000 * h
    x2 = x2 / 1000 * w

    # if x1 > x2:
    #     x1, x2 = x2, x1  # Swap x-coordinates if needed
    # if y1 > y2:
    #     y1, y2 = y2, y1  # Swap y-coordinates if needed

    annotator.box_label([x1, y1, x2, y2], label=item["label"], color=colors(idx, True))


# Image.fromarray(annotator.result())  # display the output
# Convert the result to a PIL image
annotated_img = Image.fromarray(annotator.result())

# Save to file
annotated_img.save("annotated_output.jpg")

# annotated_img = annotator.result()
# plt.imshow(np.array(annotated_img))
# plt.axis('off')
# plt.show()

# Image.fromarray(annotator.result()).show()